### ISSUE TITLE
Add Content to all Pages

### ISSUE THREAD

**Issue by Kriesse** [cssconf/2017.cssconf.eu#17]
- [x] Info
- [x] CfS (waiting for #22 to be merged)
- [x] Team (waiting for #23 to be merged) 
- [x] Sponsors (waiting for #24 to be merged)
- [x] Code of Conduct
- [x] Accessibility
- [x] Diversity Tickets
- [x] Scholarships

**Comment by Kriesse** [comment]
I created all the subpages. We still have to copy over the content from 2015, so the comms team can go over it and update it.

You can see the pages like this: http://2017.cssconf.eu/accessibility.html (this one is already done)
Old content can be found on the 2015 website: http://2015.cssconf.eu/accessibility/

**Comment by Kriesse** [comment]
Yay, all done, high fives @lukaszklis! Let's close this one and file separate issues if any page needs detail work.
